# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626e5f177cd815da192e7dd086e1ef9cfb9aaff323d4a052c0ba68146f44df72588816504a219081369925cac13238ee9e641c9de21c672e0a6ca01cb7cef8bf

test:
  secret_key_base: 74801924738911c5f4508a5d6c31f57994fa50c490fbe8514b0a10e873789929f45704a9edfe7bb6a48c3787d28daa455bba93437acff605ecb8fdf4c109fa4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
